# Generated by Django 5.2.7 on 2025-10-02 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentagem'), ('fixed', 'Valor Fixo')], max_length=10, verbose_name='Tipo de Desconto')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Desconto')),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Mínimo')),
                ('max_uses', models.IntegerField(default=1, verbose_name='Máximo de Usos')),
                ('current_uses', models.IntegerField(default=0, verbose_name='Usos Atuais')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('valid_from', models.DateTimeField(verbose_name='Válido de')),
                ('valid_until', models.DateTimeField(verbose_name='Válido até')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cupom',
                'verbose_name_plural': 'Cupons',
            },
        ),
        migrations.CreateModel(
            name='EventAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.IntegerField(default=0, verbose_name='Total de Visualizações')),
                ('total_purchases', models.IntegerField(default=0, verbose_name='Total de Compras')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Receita Total')),
                ('conversion_rate', models.FloatField(default=0, verbose_name='Taxa de Conversão')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='events.event')),
            ],
            options={
                'verbose_name': 'Analytics do Evento',
                'verbose_name_plural': 'Analytics dos Eventos',
            },
        ),
        migrations.CreateModel(
            name='TicketValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(max_length=255, unique=True, verbose_name='Código QR')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='Imagem QR')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Validado')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validado em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation', to='events.purchase')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
            ],
            options={
                'verbose_name': 'Validação de Ingresso',
                'verbose_name_plural': 'Validações de Ingressos',
            },
        ),
    ]
