# Generated by Django 5.2.7 on 2025-10-02 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_coupon_eventanalytics_ticketvalidation'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='mercado_pago_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Mercado Pago'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Status do Pagamento'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('pix', 'PIX'), ('credit_card', 'Cartão de Crédito'), ('debit_card', 'Cartão de Débito')], default='pix', max_length=20, verbose_name='Método de Pagamento'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercado_pago_id', models.CharField(max_length=100, unique=True, verbose_name='ID Mercado Pago')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Status')),
                ('payment_method', models.CharField(choices=[('pix', 'PIX'), ('credit_card', 'Cartão de Crédito'), ('debit_card', 'Cartão de Débito')], max_length=20, verbose_name='Método de Pagamento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('currency', models.CharField(default='BRL', max_length=3, verbose_name='Moeda')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('payer_email', models.EmailField(max_length=254, verbose_name='Email do Pagador')),
                ('payer_name', models.CharField(max_length=255, verbose_name='Nome do Pagador')),
                ('payer_document', models.CharField(max_length=20, verbose_name='Documento do Pagador')),
                ('pix_qr_code', models.TextField(blank=True, null=True, verbose_name='QR Code PIX')),
                ('pix_qr_code_base64', models.TextField(blank=True, null=True, verbose_name='QR Code PIX Base64')),
                ('card_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token do Cartão')),
                ('installments', models.IntegerField(default=1, verbose_name='Parcelas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('mp_response', models.JSONField(blank=True, null=True, verbose_name='Resposta MP')),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='events.purchase', verbose_name='Compra')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
