# Generated by Django 5.2.7 on 2025-10-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='mp_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Status MP'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='preference_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID da Preferência'),
        ),
    ]
