# Generated by Django 5.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_purchase_mercado_pago_id_purchase_payment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True, verbose_name='ID do Evento')),
                ('event_type', models.CharField(choices=[('payment', 'Pagamento'), ('plan', 'Plano'), ('subscription', 'Assinatura'), ('invoice', 'Fatura'), ('point_integration_whitelist', 'Integração Ponto')], max_length=50, verbose_name='Tipo do Evento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processed', 'Processado'), ('failed', 'Falhou'), ('ignored', 'Ignorado')], default='pending', max_length=20, verbose_name='Status')),
                ('raw_data', models.JSONField(verbose_name='Dados Brutos')),
                ('processed_data', models.JSONField(blank=True, null=True, verbose_name='Dados Processados')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Recebido em')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('signature_valid', models.BooleanField(default=False, verbose_name='Assinatura Válida')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origem')),
            ],
            options={
                'verbose_name': 'Evento Webhook',
                'verbose_name_plural': 'Eventos Webhook',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=10, verbose_name='Nível')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Detalhes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('webhook_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='communication.webhookevent', verbose_name='Evento Webhook')),
            ],
            options={
                'verbose_name': 'Log Webhook',
                'verbose_name_plural': 'Logs Webhook',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('payment_approved', 'Pagamento Aprovado'), ('payment_rejected', 'Pagamento Rejeitado'), ('payment_cancelled', 'Pagamento Cancelado'), ('payment_refunded', 'Pagamento Reembolsado'), ('payment_pending', 'Pagamento Pendente')], max_length=30, verbose_name='Tipo de Notificação')),
                ('payment_id', models.CharField(max_length=100, verbose_name='ID do Pagamento')),
                ('external_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referência Externa')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('currency', models.CharField(default='BRL', max_length=3, verbose_name='Moeda')),
                ('payment_status', models.CharField(max_length=50, verbose_name='Status do Pagamento')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Método de Pagamento')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('webhook_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_notification', to='communication.webhookevent', verbose_name='Evento Webhook')),
            ],
            options={
                'verbose_name': 'Notificação de Pagamento',
                'verbose_name_plural': 'Notificações de Pagamento',
                'ordering': ['-created_at'],
            },
        ),
    ]